sonar.organization=kt-npm-modules
sonar.projectKey=kt-npm-modules_npm-typescript-template
sonar.projectName=npm-typescript-template

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage*/**/lcov.info

# sonar.exclusions=src/routes/**/*
sonar.cpd.exclusions=tests/**/*,
