sonar.organization=mirasen-io
sonar.projectKey=mirasen-io_react-chessboard
sonar.projectName=react-chessboard

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage*/**/lcov.info

sonar.cpd.exclusions=tests/**/*,
